## Overview
* Intro to tensors
* Information to tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function (a way to speed up python functions)
* Using GPUs and Tensorflow
* Misc. Excerecises

### Intro to tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check number of dimensions of tensor (ndim)
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimensions of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[2,3],[1,6]])

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[10.,7.,2.],[3.,6.,12.]],dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[10.,  7.,  2.],
       [ 3.,  6., 12.]], dtype=float16)>

In [9]:
# number of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# create a tensor having
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

* Scalar : single dimension
* Vector : a number with direction
* Matrix : 2-dimensional array of numbers
* Tensor : a n-dimensional array of numbers

In [11]:
# Creating tensors with tf.Variable()
changable_tensor = tf.Variable([2,3])
unchangable_tensor = tf.constant([3,2])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>)

In [12]:
# changing values in tensor (changable)
changable_tensor[0].assign(3)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3], dtype=int32)>

**Note**: Use tensor.constant most likely only if required and change later as tf will handle the creation in most cases

#### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [13]:
# Create 2 random (but same) tensors
random_1 = tf.random.Generator.from_seed(23) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(23)
random_2 = random_2.normal(shape=(3,2))

# check for equality
random_1, random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892],
        [-1.5700307 ,  0.4457582 ],
        [ 0.10944034, -0.8035768 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892],
        [-1.5700307 ,  0.4457582 ],
        [ 0.10944034, -0.8035768 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

#### Shuffle order of elements in a tensor


In [14]:
# shuffle a tensor (helps shuffle the data so inherent position does not affect tyhe learning)
not_shuffled = tf.constant([[1,2],[3,4],[5,6]])
not_shuffled.ndim

# shufling the tensor (along 1st dimension)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [15]:
# shufling the tensor (along 1st dimension)
tf.random.set_seed(23)   # global level random seed
tf.random.shuffle(not_shuffled,seed=23) # local level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [16]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

Shuffled tensors to be in the same order use both global and local level random seed.

In [17]:
# other way to make tensors
tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
#creating tensor of al zeros
tf.zeros(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The main difference between numpy arrays and tensors is that tensors can be run on a gpu at faster speeds

In [19]:
# converting numpy arrays to tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # use capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [23]:
2 * 3 * 4 # shape must be equal to the original length of the array/tensor

24

In [24]:
A.ndim

3

#### Getting information from *tensors*

When dealing with tensors we need to be aware of the following attributes:
* shape
* rank (ndim)
* axis or dimension
* size

In [25]:
# create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
2 * 3 * 4 * 5

120

In [29]:
rank_4_tensor.shape , rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
# get various attributses of tensors
print('Datatype of every element: ', rank_4_tensor.dtype)
print('Number of dimensions (rank): ', rank_4_tensor.ndim)
print('Shape of tensor: ', rank_4_tensor.shape)
print('Elements along the 0 axis: ', rank_4_tensor.shape[0])
print('Element along the last axis: ',rank_4_tensor.shape[-1])
print('Total number of elements in our tensor', tf.size(rank_4_tensor))
print('Total number of elements in our tensor', tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Element along the last axis:  5
Total number of elements in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor 120


### Indexing tensors
Tensors can be indexed like python lists

In [33]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [34]:
# get the forst 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# get first index from each dimesion except the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# get first index from each dimesion except the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [40]:
# create a rank 2 tensor
rank_2_tensor = tf.constant([[1,2],[3,4]])
rank_2_tensor, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 2)

In [42]:
# get last value of the tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [43]:
# adding extra dimensions toout rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [110]:
 # alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [49]:
 tf.expand_dims(rank_2_tensor,axis=0) # expand 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic operations**
`+`,`-`,`*`,`/`

In [50]:
tensor = tf.constant([[1,2],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [51]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [53]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [54]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [55]:
# We can use the tensorflow built in functions for the same operations
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

**Matrix multiplication in tensors**

In machine learning matrix multiplication is one of the most used operations

In [61]:
# matrix multiplication in tensorflow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [62]:
tensor * tensor # unit wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [63]:
# matrix multiplication in python has operator `@`
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

Matrix multiplication on tensors of different shapes

In [64]:
# Create a tensor (3,2) tensor
X = tf.random.Generator.from_seed(23)
X = X.normal(shape=(3,2))

# Another tensor of same shape
Y = tf.random.Generator.from_seed(32)
Y = Y.normal(shape=(3,2))

In [66]:
# tf.matmul(X,Y) -- this does not work due to incompatable shapes inner dimesions must match

Solution:

In [70]:
# change the shape of y
tf.reshape(Y, shape=(2,3))
Y

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.7901182,  1.585549 ],
       [ 0.4356279,  0.2364518],
       [-0.1589871,  1.302304 ]], dtype=float32)>

In [73]:
# now X with  reshaped Y
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.10113779,  0.18082248,  0.09670806],
       [-1.1351095 , -2.5602303 , -0.10343647],
       [-0.10353639,  0.3012814 , -0.99882615]], dtype=float32)>

OR

In [74]:
# use transpose of the tensor
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.14827378,  0.05946834,  0.02681255],
       [-0.53373843, -0.57854885,  0.83012736],
       [-1.1876396 , -0.14233193, -1.063901  ]], dtype=float32)>

In [75]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.60847235, -0.04233468],
       [ 0.34954894, -0.8857037 ]], dtype=float32)>

**The dot product**

Matrix multiplication is referred to as dot product this can be done using ;-
* `tf.matmul`
* `tf.tensordot`

In [76]:
# perfrom dot product on X and Y
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.60847235, -0.04233468],
       [ 0.34954894, -0.8857037 ]], dtype=float32)>

In [78]:
# do matrix multiplication with both transpose and reshape
tf.tensordot(X, tf.transpose(Y), axes=1) , tf.tensordot(X,tf.reshape(Y,shape=(2,3)),axes=1)

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.14827378,  0.05946834,  0.02681255],
        [-0.53373843, -0.57854885,  0.83012736],
        [-1.1876396 , -0.14233193, -1.063901  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.10113779,  0.18082248,  0.09670806],
        [-1.1351095 , -2.5602303 , -0.10343647],
        [-0.10353639,  0.3012814 , -0.99882615]], dtype=float32)>)

In [81]:
# Check values of Y, transposed Y, reshaped Y
print('Normal Y:')
print(Y, '\n')

print('Y reshaped:') # here the values are shuffled to fit shape
print(tf.reshape(Y,shape=(2,3)), '\n')

print('Y transposed:') # here axis is swapped not shuffling
print(tf.transpose(Y), '\n')

Normal Y:
tf.Tensor(
[[ 0.7901182  1.585549 ]
 [ 0.4356279  0.2364518]
 [-0.1589871  1.302304 ]], shape=(3, 2), dtype=float32) 

Y reshaped:
tf.Tensor(
[[ 0.7901182  1.585549   0.4356279]
 [ 0.2364518 -0.1589871  1.302304 ]], shape=(2, 3), dtype=float32) 

Y transposed:
tf.Tensor(
[[ 0.7901182  0.4356279 -0.1589871]
 [ 1.585549   0.2364518  1.302304 ]], shape=(2, 3), dtype=float32) 



Generally, when performing matrix multiplication on two tensors you will usually transpose one of the two tensors to satisfy the rules of matrix multiplication

**Changing the datatype of a tensor**

usually the default is int32

In [82]:
# create the new tensor with default datatype (float32)
B = tf.constant([1.1, 2.2])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2.2], dtype=float32)>

In [83]:
C = tf.constant([2,3])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [86]:
# convert from float32 to float16 -- reducing the precision
D = tf.cast(B, dtype=tf.float16)
D , D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.1, 2.2], dtype=float16)>,
 tf.float16)

16 bit precision is faster to compute than 32 bit precision

**Aggregating tensors**

Aggregating tensors = condensing them from multiple values doen to a smaller amount of values

In [87]:
# Getting the absolute values
D = tf.constant([-3,-2])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -2], dtype=int32)>

In [88]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

Other forms of aggregation:
* get the minimum
* get the maximum
* get the mean of a tensor
* get the sum of the tensor

In [90]:
# Creae a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98, 23, 67, 42, 22, 95, 17, 12, 51,  2, 29, 65, 10,  7, 80, 68, 80,
       25, 67,  2, 75, 69, 66, 52, 79, 86, 32, 93, 51,  4, 94, 46, 84, 85,
        0, 43, 40, 12, 75, 95, 71, 21, 63, 55, 98, 12, 79, 16, 47, 25])>

In [92]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [93]:
# find the mimimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [94]:
# find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [95]:
# mean of the tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [96]:
# sum of the tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2530>

In [108]:
# Varience and standard deviation of the tensor
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=941>

Alternately,

In [112]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=941.52>

In [111]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.684198>

**Find the positional maximum and minimum of a tensor**

(helps fond the max probability in the output of the NN -- one hot encode the out)

In [117]:
# creating a random tensor
tf.random.set_seed(23)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
       0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
       0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
       0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
       0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
       0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
       0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
       0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
       0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
       0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487],
      dtype=float32)>

In [118]:
# finding positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [119]:
# index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [120]:
#Confirm the largest value in the F tensor
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [121]:
# confirming the max
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [122]:
# positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [123]:
# finding minimum using positional index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.012452364>

### Squeezing the tensor (removing all single dimensions)


In [129]:
# create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [130]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [132]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [133]:
# create a list of indices
some_list = [0, 1, 2, 3] # could be red, blue, green, blue

In [134]:
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [135]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth=len(some_list), on_value=1, off_value=-1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1, -1, -1, -1],
       [-1,  1, -1, -1],
       [-1, -1,  1, -1],
       [-1, -1, -1,  1]], dtype=int32)>

#### Some more Math functions

In [136]:
# create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [137]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [139]:
# find the square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [142]:
# find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensorflow with numpy**

Tensorflow interacts with numpy easily ->
* numpy built on the array
* tf builf on tensor

In [143]:
# create tensor from numpy array and vice versa
J = tf.constant([1,2,3,4])
J

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [144]:
np.array(J) , type(np.array(J))

(array([1, 2, 3, 4], dtype=int32), numpy.ndarray)

In [146]:
J.numpy(), type(J.numpy())

(array([1, 2, 3, 4], dtype=int32), numpy.ndarray)

Default values of:
* float64 -> tensor from numpy
* float32 -> tensor from tensor